### ISSUE TITLE
스킨 너무 잘 쓰고 있습니다!! 한가지 문의 사항이 있습니다!

### ISSUE THREAD

**Issue by jminie-o8o** [bluemiv/tistory_berry_skin#109]
안녕하세요 bluemiv님!
우선 너무나 모던하고 이쁜 스킨 제공해주셔서 감사합니다! 제가 본 스킨중에 제일 이뻐요...! 정말..
한가지 문의사항이 있어서요! 
현재 글을 등록하면 자동으로 제목에 넘버링이 붙게 되는데요!

</br>

<img width="235" alt="image" src="https://user-images.githubusercontent.com/79504043/205559241-3436c834-1a6a-4099-b16d-156c0b29fff6.png">

</br>

해당 넘버링을 원하지 않은 경우 없앨 수 있는 방법이 있나요??

**Comment by bluemiv** [comment]
현재 버전 3을 개발 진행하고 있습니다. 3버전 만들면서 말씀해주신 의견 반영해보록 하겠습니다

**Comment by jminie-o8o** [comment]
@bluemiv 네 감사합니다!!

**Comment by bluemiv** [comment]
3.0.0으로 배포되었습니다. 스킨편집에서 설정할 수 있습니다. 기본적으로는 노출됩니다
