### ISSUE TITLE
메인화면 관련입니다 !

### ISSUE THREAD

**Issue by mudrhs1997** [bluemiv/tistory_berry_skin#110]
최초 블로그 들어갔을 때의 홈 화면에서 글쓰기 및 블로그 관리 버튼이 눌리지가 않습니다 !
글에 들어가서는 잘 눌립니다

**Comment by bluemiv** [comment]
특정 상황에서 오류가 발생하면서 뒤에 js 스크립트가 실행이 안된 것으로 보이네요. 3.0 버전을 만들고 있는중이라, 해당 버전에서 개선하겠습니다

**Comment by bluemiv** [comment]
3.0.0으로 배포되었습니다.
