### ISSUE TITLE
다크모드에서 글자색 오류에 대한 이슈로 질문드려요!

### ISSUE THREAD

**Issue by devkoow** [bluemiv/tistory_berry_skin#143]
베리님! 배포해주신 스킨을 사용 중인데, 글 작성 탭에서 글자색을 '없음'으로 해서 기본으로 해둬도 다크모드에서 자꾸 하얀색으로 자동전환이 다 안되고 중간 중간 몇줄씩 회색이나 검은색으로 적용되는 오류가 계속 발생하는데요... 혹시 이 문제에 대해서 도움 받을 수 있을까요?

**Comment by devkoow** [comment]
![오류](https://github.com/bluemiv/tistory_berry_skin/assets/112608822/312398da-128e-43ab-9132-1430f05db3a6)

**Comment by bluemiv** [comment]
티스토리 글 작성하실때 따로 색상 넣으신거 같아요
글 색상 제거하시면 될거 같습니다

**Comment by devkoow** [comment]
글 작성할 때 색상 안 넣고 오류때문에 '없음'으로 전체를 다 지정해서 '없음'으로 해도 저렇게 되네요..
흰색으로 하면 당연히 라이트모드일때 글자가 안 보이고 CSS문제인지 원인을 모르겠습니다.
