### ISSUE TITLE
안녕하세요! 다크테마 모드 개발은 어떠하신지요..?

### ISSUE THREAD

**Issue by MINSU-96** [bluemiv/tistory_berry_skin#53]
안녕하세요!
베리스킨 정말 잘쓰고 있습니다. Gatsby로 구현하려다 이것저것 막혀서 낙담하던 차에 기대하던 느낌이랑 정말 동일한 berry skin을 만나게 되었습니다.
다시 한번 정말 감사합니다.

혹시 시간적 리소스가 괜찮으시다면, 다크모드(테마) 개발을 부탁드려도 될까요?? 이외의 기능은 모두 잘쓰고 있습니다.

감사합니다. 항상 건강 조심하시고, 행복한 일 가득하세요.

**Comment by bluemiv** [comment]
요즘 일이 좀 바빠서 신경을 많이 못썼습니다.

메일 확인했었는데, 답장 보낸다는걸 깜빡했네요

안그래도, 관리를 너무 안하긴해서 조만간 업데이트를 할 생각입니다. 이렇게 의견 주셔서 감사드립니다. @MINSU-96
