### ISSUE TITLE
그림 크기 수정좀 부탁드려요

### ISSUE THREAD

**Issue by SunWooChan** [bluemiv/tistory_berry_skin#60]
그림 크기가 작던 크던 간에 항상 최대사이즈로 보여줍니다.

글 작성 시 작은 사이즈로 보여주고 싶어서 작은 사이즈로 축소를 시켜도, 포스팅을 완료하면 좌우를 꽉 채우는 방식으로 나타납니다.

좋은 스킨 배포해주셔서 감사합니다.

**Comment by bluemiv** [comment]
일부러 채워지도록 했는데, 해당 기능은 다음버전에 개선하도록 하겠습니다.

**Comment by bluemiv** [comment]
v2.1.0 버전으로 배포했습니다
