### ISSUE TITLE
모바일로 글을 볼 때, 블로그 구독과 다크모드, 페이지 위로가기 버튼 위치

### ISSUE THREAD

**Issue by seoro-ha** [bluemiv/tistory_berry_skin#63]
Bluemiv님 안녕하세요.
공유해주시는 블로그 테마는 너무 잘 사용하고 있습니다. 
먼저 감사하다는 말씀을 드립니다. 

한 가지 건의사항이 있어요!
블로그 글을 모바일로 볼 때 블로그 구독, 다크모드, 페이지 상단으로 가기 버튼이 텍스트를 가려 텍스트를 읽기에 다소 불편한 점이 있었습니다. 버튼의 위치가 최하단에 위치할 수 있도록 수정해주신다면 텍스트 가시성이 훨씬 좋아지리라 생각합니다.

반영이 어렵다면, 개인적으로 수정할 수 있는 방법을 간단히나마 알려주실 수 있다면 너무 감사하겠습니다^^

감사합니다!

**Comment by bluemiv** [comment]
넵 제가 보기에도 불편한 부분이 있네요. 개선하도록 하겠습니다
