### ISSUE TITLE
파이썬 코드 첫줄 중복 문제

### ISSUE THREAD

**Issue by dorulog** [bluemiv/tistory_berry_skin#64]
안녕하세요. 좋은 스킨 잘 사용하고 있습니다.
다만 제 블로그에 적용시에 
파이썬 코드 위치에 
첫줄이 중복되서 안보이는 문제점이 있는데요.
이 경우에 어떻게 해야할까요?
<img width="667" alt="image" src="https://user-images.githubusercontent.com/84913626/174421704-019f10a4-5792-406b-bbc3-4e08600ccf5a.png">

**Comment by bluemiv** [comment]
정확한 재현 스텝은 모르겠지만, javascript 파일이 추가가 안됐을수도 있을거 같습니다.

javascript 파일이 제대로 추가되었는지 확인 부탁드립니다.

그래도 안되신다면, 블로그 주소와 상세한 재현스텝 알려주시면 감사드리겠습니다.

**Comment by dorulog** [comment]
안녕하세요. 파일은 정상적으로 업로드 되었구요.
https://dorudoru.tistory.com/2259
이 주소 외에도 다른 페이지에서도 동일현상이 발생합니다.
감사합니다.

**Comment by bluemiv** [comment]
관리자 페이지에서 코드 문법강조 플러그인 적용해주세요
<img width="312" alt="image" src="https://user-images.githubusercontent.com/26136312/175217654-6a50d54d-af49-42cd-944c-03107f4b08f8.png">

**Comment by dorulog** [comment]
> 
잘 해결하였습니다.
너무 감사합니다!
