### ISSUE TITLE
업데이트를 하고 다크모드 버그??

### ISSUE THREAD

**Issue by AsickAsack** [bluemiv/tistory_berry_skin#75]
다크모드를 적용 후에 블로그를 들어가거나 새로운 글을 누르면 잠깐 화이트모드로 갔다가 다크모드로 돌아오는 버그가 있습니다.
저만 이런건가요?

그리고 글자에 배경색을 적용해도 적용이 안됩니다..(전 버전에서도 그랬습니다)

**Comment by bluemiv** [comment]
잠깐 light theme에서 dark theme로 변경되는 이유는 알거 같네요. 수정해서 다시 올릴께요

글자에 배경색 적용해도 안되는건 원인 분석 후 적용하겠습니다.

**Comment by bluemiv** [comment]
v2.2.0  배포했습니다.
