### ISSUE TITLE
안녕하세요

### ISSUE THREAD

**Issue by SunWooChan** [bluemiv/tistory_berry_skin#78]
스킨 너무나 잘쓰고 있습니다. 정말 감사드려요!
혹시 특수문자가 작성 완료 후 안보이는데 적용해주실 수 있나요?
기본적인 곱하기 나누기 뿐만 아니라 θ, φ 같은 수학적 수식도 적용되면 좋겠습니다. 감사합니다.

**Comment by bluemiv** [comment]
v2.2.0  배포했습니다.
