### ISSUE TITLE
보호글 관련 건의사항

### ISSUE THREAD

**Issue by Veloideu** [bluemiv/tistory_berry_skin#84]
안녕하세요. 이번에 berry_skin이 너무 이뻐서 쓰게 된 사람입니다.

다름이 아니라 게시글을 쓰고 보호글로 지정을 하면, 목록에는 (1)에 글이 표시되지만
비밀번호 입력 창 및 목록에 보호글을 확인 할 수 없습니다. (*로그인 된 사용자[관리자])만 보이게 됩니다.

위와 같이 보호글 문제점이 있는데, 해결해주시면 감사합니다.

**Comment by bluemiv** [comment]
3버전 개발 진행중입니다. 해당 버전에서 개선해도록 하겠습니다.
감사합니다.

**Comment by bluemiv** [comment]
3.0.0으로 배포되었습니다.

**Comment by Veloideu** [comment]
개선해주셔서 감사합니다 :)
